name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Check GCC version"
        run: "gcc --version"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('test_requirements.txt') }}
      - name: "Install dependencies"
        run: |
          # Install torch first because we need the headers for torch-scatter, etc.
          pip install `cat test_requirements.txt | grep torch==`
          pip install -r test_requirements.txt
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
