name: Simulation-Based Graph Inference

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check GCC version"
        run: "gcc --version"
      - uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-path: uv.lock
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install project
        run: uv sync --all-groups
      - name: "Build the project"
        run: "uv run make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
