name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
      - name: "Check GCC version"
        run: "gcc --version"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('test_requirements.txt') }}
      - name: "Install dependencies"
        run: |
          # Install cython first because we need it for setup.py.
          pip install `cat test_requirements.txt | grep cython==`
          pip install `cat test_requirements.txt | grep torch==`
          pip install -r test_requirements.txt
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
